name: face_attendance
description: Aplicación Flutter de asistencia con reconocimiento facial offline usando MobileFaceNet.tflite
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.1
  google_mlkit_commons: ^0.8.1
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  path_provider: ^2.1.2
  path: ^1.9.0

  # === Base de datos cifrada ===
  sqflite_sqlcipher: ^3.4.0

  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  file_picker: ^8.1.4
  collection: ^1.18.0
  intl: ^0.19.0
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilefacenet_112x112_128d.tflite
    - assets/images/                  # Declara la carpeta de imágenes
    - assets/images/logo_dataface.png # Declara el logo DF
    - assets/images/logo_sioma.png    # Declara el logo SIOMA